# Generated by Django 5.2.4 on 2025-07-10 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('retired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GearSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_used', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0)),
                ('climb', models.FloatField(default=0.0)),
                ('session_count', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitnesslog_app.gear')),
            ],
        ),
    ]
