# Generated by Django 5.2.4 on 2025-07-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GearSummary',
            new_name='GearCalculated',
        ),
    ]
