# Generated by Django 5.2.4 on 2025-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0003_activity_activitydaycalculated_hrzones_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('severity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('start_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both'), ('', '')], default='', max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('severity', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='hrzones',
            name='zone_multipliers',
            field=models.JSONField(default=list),
        ),
    ]
