# Generated by Django 5.2.4 on 2025-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0004_illness_injury_alter_hrzones_zone_multipliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityauto',
            name='file',
            field=models.FileField(default=0, upload_to='activity_files_uploads/'),
            preserve_default=False,
        ),
    ]
