# Generated by Django 5.2.4 on 2025-07-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0006_alter_activityauto_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.TextField(blank=True),
        ),
    ]
