# Generated by Django 5.2.4 on 2025-07-10 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0007_activity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='locations',
        ),
    ]
