# Generated by Django 5.2.4 on 2025-07-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0008_remove_activity_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityauto',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='fitnesslog_app.activity'),
        ),
    ]
