# Generated by Django 5.2.4 on 2025-07-10 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0009_alter_activityauto_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='feeling',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Terrible'), (2, 'Awful'), (3, 'Very bad'), (4, 'Not great'), (5, 'Meh'), (6, 'Okay'), (7, 'Good'), (8, 'Very good'), (9, 'Excellent'), (10, 'Euphoric')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='intensity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Leisure'), (2, 'Very easy'), (3, 'Easy'), (4, 'Steady'), (5, 'Moderate'), (6, 'Brisk'), (7, 'Quick'), (8, 'Hard'), (9, 'Very hard'), (10, 'Max')], null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fitnesslog_app.sport'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='terrain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_at_HR',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_at_pace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
