# Generated by Django 5.2.4 on 2025-07-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0010_alter_activity_activity_type_alter_activity_feeling_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityauto',
            old_name='activity',
            new_name='sport',
        ),
    ]
