# Generated by Django 5.2.4 on 2025-07-10 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0011_rename_activity_activityauto_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityauto',
            name='activity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='fitnesslog_app.activity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activityauto',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityautos', to='fitnesslog_app.sport'),
        ),
    ]
