# Generated by Django 5.2.4 on 2025-07-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0012_activityauto_activity_alter_activityauto_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityauto',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto', to='fitnesslog_app.activity'),
        ),
    ]
