# Generated by Django 5.2.4 on 2025-07-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0013_alter_activityauto_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
