# Generated by Django 5.2.4 on 2025-07-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0014_alter_activity_start_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearcalculated',
            name='time_elapsed',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
