# Generated by Django 5.2.4 on 2025-08-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0016_rename_start_datetime_activity_start_datetime_utc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityauto',
            name='activity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityauto', to='fitnesslog_app.activity'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
