# Generated by Django 5.2.4 on 2025-08-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0017_alter_activityauto_activity_alter_sport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='start_datetime',
            field=models.DateField(),
        ),
    ]
