# Generated by Django 5.2.4 on 2025-08-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0018_alter_illness_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='illness',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
