# Generated by Django 5.2.4 on 2025-08-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0019_rename_start_datetime_illness_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='elapsed_time',
            new_name='time_elapsed',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='moving_time',
            new_name='time_moving',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='tracked_time',
            new_name='time_tracked',
        ),
        migrations.RenameField(
            model_name='activityauto',
            old_name='elapsed_time',
            new_name='time_elapsed',
        ),
        migrations.RenameField(
            model_name='activityauto',
            old_name='moving_time',
            new_name='time_moving',
        ),
        migrations.RenameField(
            model_name='activityauto',
            old_name='tracked_time',
            new_name='time_tracked',
        ),
    ]
