# Generated by Django 5.2.4 on 2025-08-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0020_rename_elapsed_time_activity_time_elapsed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type',
            new_name='activity_type_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='calories',
            new_name='calories_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='distance',
            new_name='distance_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_gain',
            new_name='elevation_gain_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_loss',
            new_name='elevation_loss_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_max',
            new_name='elevation_max_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_min',
            new_name='elevation_min_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='feeling',
            new_name='feeling_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='gear',
            new_name='gear_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='intensity',
            new_name='intensity_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='location',
            new_name='location_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='note',
            new_name='note_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='sport',
            new_name='sport_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_datetime_utc',
            new_name='start_datetime_utc_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='start_timezone',
            new_name='start_timezone_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='terrain',
            new_name='terrain_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_at_HR',
            new_name='time_at_HR_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_at_pace',
            new_name='time_at_pace_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_elapsed',
            new_name='time_elapsed_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_moving',
            new_name='time_moving_raw',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_tracked',
            new_name='time_tracked_raw',
        ),
    ]
