# Generated by Django 5.2.4 on 2025-08-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesslog_app', '0021_rename_activity_type_activity_activity_type_raw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_type_raw',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='calories_raw',
            new_name='calories',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='distance_raw',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_gain_raw',
            new_name='elevation_gain',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_loss_raw',
            new_name='elevation_loss',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_max_raw',
            new_name='elevation_max',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='elevation_min_raw',
            new_name='elevation_min',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='feeling_raw',
            new_name='feeling',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='gear_raw',
            new_name='gear',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='intensity_raw',
            new_name='intensity',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='location_raw',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='note_raw',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='sport_raw',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='terrain_raw',
            new_name='terrain',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_at_HR_raw',
            new_name='time_at_HR',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_at_pace_raw',
            new_name='time_at_pace',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_elapsed_raw',
            new_name='time_elapsed',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_moving_raw',
            new_name='time_moving',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='time_tracked_raw',
            new_name='time_tracked',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_datetime_utc_raw',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_timezone_raw',
        ),
    ]
